import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashboard using Ant Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Homepage</h2>
      <p>Welcome to the homepage</p>
      <p>Navigate to your desired page from the sidebar</p>
    </div>
  )
}
